server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/usechesilva123/configuration-ubacademico
          username: usechesilva@hotmail.es
          password: 
          search-paths:
           - '*service'
